#!/usr/bin/env python3
"""Render the scoped structural-realization projection.

The declared authority set comes from architecture/state_authorities.json.
A matching projection proves equality to that authority set only; it does not
prove repository-wide completeness or exact-head execution success.
"""
from __future__ import annotations

import argparse
import difflib
import json
from collections import Counter, defaultdict
from pathlib import Path

from architecture.state_authorities import (
    ROOT,
    load_manifest,
    projection_authority_paths,
    projection_fingerprint,
    surface_by_id,
)

DEFAULT_OUTPUT = ROOT / "docs" / "generated" / "STATUS.md"


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _partition_authorities(root: Path, paths: list[Path]) -> dict[str, list[Path]]:
    groups = {
        "modules": [],
        "claims": [],
        "evidence": [],
        "experiments": [],
        "sheaf": [],
    }
    for path in paths:
        relative = path.relative_to(root).as_posix()
        if relative.startswith("architecture/modules/") and relative.endswith(".json"):
            groups["modules"].append(path)
        elif relative == "claims/registry.json":
            groups["claims"].append(path)
        elif relative == "evidence/registry.json":
            groups["evidence"].append(path)
        elif relative.startswith("experiments/") and relative.endswith(".json"):
            groups["experiments"].append(path)
        elif relative == "methods/sheaf-realization.v1.json":
            groups["sheaf"].append(path)
        else:
            raise ValueError(
                "structural-realization authority has no renderer semantics: "
                + relative
            )
    if len(groups["claims"]) != 1 or len(groups["evidence"]) != 1 or len(groups["sheaf"]) != 1:
        raise ValueError(
            "structural-realization authority requires exactly one claim registry, "
            "evidence registry, and sheaf-realization authority"
        )
    if not groups["modules"] or not groups["experiments"]:
        raise ValueError(
            "structural-realization authority requires module registries and experiments"
        )
    return groups


def _module_records(root: Path, paths: list[Path]) -> list[tuple[str, dict]]:
    records: list[tuple[str, dict]] = []
    for path in sorted(paths):
        payload = _load_json(path)
        lifecycle = path.stem
        for record in payload.get("modules", []):
            records.append((lifecycle, record))
    return records


def _claim_records(path: Path) -> list[dict]:
    return _load_json(path).get("claims", [])


def _evidence_records(path: Path) -> list[dict]:
    return _load_json(path).get("evidence", [])


def _experiment_records(root: Path, paths: list[Path]) -> list[tuple[str, dict]]:
    return [
        (path.relative_to(root).as_posix(), _load_json(path))
        for path in sorted(paths)
    ]


def _sheaf_obligations(path: Path) -> list[dict]:
    return _load_json(path).get("obligations", [])


def render_status(root: Path = ROOT) -> str:
    manifest = load_manifest()
    surface = surface_by_id(manifest, "structural_realization")
    authority_paths = projection_authority_paths(root, manifest, "structural_realization")
    fingerprint = projection_fingerprint(root, manifest, "structural_realization")
    groups = _partition_authorities(root, authority_paths)

    modules = _module_records(root, groups["modules"])
    claims = _claim_records(groups["claims"][0])
    evidence = _evidence_records(groups["evidence"][0])
    experiments = _experiment_records(root, groups["experiments"])
    obligations = _sheaf_obligations(groups["sheaf"][0])

    lifecycle_counts = Counter(lifecycle for lifecycle, _ in modules)
    maturity_counts = Counter(record.get("maturity", "unknown") for _, record in modules)
    claim_maturity_counts = Counter(record.get("maturity", "unknown") for record in claims)
    validated_claims = sum(
        1
        for record in claims
        if record.get("maturity") in {"validated", "replicated", "decision-eligible"}
    )

    lines = [
        "# Generated structural repository projection",
        "",
        "<!-- Generated by architecture/render_status.py. Do not hand-edit. -->",
        "",
        "This file is a deterministic projection of a **declared structural-realization authority set**, not a complete repository-status snapshot.",
        "",
        f"Authority-set fingerprint: `{fingerprint}`.",
        "",
        "Declared inputs:",
        "",
    ]
    for path in authority_paths:
        lines.append(f"- `{path.relative_to(root).as_posix()}`")

    lines.extend([
        "",
        "A successful freshness check means only that this file matches those inputs. It does **not** establish planning state, exact-head CI success, empirical validation, GPU correctness, scientific priority, committed evaluation outcomes that are not promoted through the declared evidence authorities, commit-history state, or unregistered implementation facts.",
        "",
        "Explicitly excluded from this projection:",
        "",
    ])
    for exclusion in surface.get("excludes", []):
        lines.append(f"- {exclusion}")

    lines.extend([
        "",
        "Repository-wide present-state conclusions require the commit-scoped reconciliation protocol in `docs/REPOSITORY-STATE.md`.",
        "",
        "External implementation ownership is not treated as local realization. A Climate result that depends on a native external data/model/evaluation capability becomes reproducible only when the corresponding adapter/import path binds exact upstream identity, configuration, transformations, failures, and receipts; availability of the external project alone proves none of those facts.",
        "",
        f"**Validated claims: {validated_claims} · Registered evidence records: {len(evidence)}**",
        "",
        "## Module authority",
        "",
        f"Registered modules: **{len(modules)}**.",
        "",
        "| Lifecycle | Count |",
        "| --- | ---: |",
    ])
    for lifecycle, count in sorted(lifecycle_counts.items()):
        lines.append(f"| `{lifecycle}` | {count} |")

    lines.extend([
        "",
        "| Declared maturity | Count |",
        "| --- | ---: |",
    ])
    for maturity, count in sorted(maturity_counts.items()):
        lines.append(f"| `{maturity}` | {count} |")

    lines.extend([
        "",
        "### Canonical and reference modules",
        "",
        "| Registry | Authority | Path | Family | Maturity | Scientific evidence eligible |",
        "| --- | --- | --- | --- | --- | --- |",
    ])
    for lifecycle, record in sorted(modules, key=lambda item: (item[0], item[1]["path"])):
        if lifecycle not in {"canonical", "reference"}:
            continue
        eligible = "yes" if record.get("scientific_evidence_eligible") else "no"
        lines.append(
            f"| `{lifecycle}` | `{record.get('authority_kind', 'unknown')}` | "
            f"`{record['path']}` | `{record.get('family', '')}` | "
            f"`{record.get('maturity', 'unknown')}` | {eligible} |"
        )

    lines.extend([
        "",
        "## Scientific claims",
        "",
        f"Registered claims: **{len(claims)}**.",
        "",
        "| Maturity | Count |",
        "| --- | ---: |",
    ])
    for maturity, count in sorted(claim_maturity_counts.items()):
        lines.append(f"| `{maturity}` | {count} |")

    lines.extend([
        "",
        "| Claim | Type | Maturity | Supporting evidence records |",
        "| --- | --- | --- | ---: |",
    ])
    for claim in sorted(claims, key=lambda item: item["claim_id"]):
        lines.append(
            f"| `{claim['claim_id']}` | `{claim.get('claim_type', '')}` | "
            f"`{claim.get('maturity', 'unknown')}` | "
            f"{len(claim.get('supporting_evidence', []))} |"
        )

    lines.extend([
        "",
        "## Registered experiments",
        "",
        f"Experiment specifications: **{len(experiments)}**.",
        "",
        "| Experiment | File |",
        "| --- | --- |",
    ])
    for relative, experiment in experiments:
        lines.append(
            f"| `{experiment.get('experiment_id', '<missing>')}` | `{relative}` |"
        )

    if obligations:
        by_layer: dict[str, Counter] = defaultdict(Counter)
        for obligation in obligations:
            status = obligation.get("status", "unknown")
            by_layer[obligation.get("layer", "unknown")][status] += 1
        reference_realized = sum(
            1 for item in obligations if item.get("status") == "reference_realized"
        )
        canonical_realized = sum(
            1 for item in obligations if item.get("status") == "canonical_realized"
        )
        validated = sum(1 for item in obligations if item.get("status") == "validated")
        open_count = sum(1 for item in obligations if item.get("status") == "open")
        realized = reference_realized + canonical_realized + validated
        lines.extend([
            "",
            "## Sheaf realization frontier",
            "",
            f"Obligations: **{realized} realized / {open_count} open / {len(obligations)} total** "
            f"({reference_realized} reference, {canonical_realized} canonical, {validated} validated).",
            "",
            "| Layer | Reference | Canonical | Validated | Open |",
            "| --- | ---: | ---: | ---: | ---: |",
        ])
        for layer in sorted(by_layer):
            lines.append(
                f"| `{layer}` | {by_layer[layer].get('reference_realized', 0)} | "
                f"{by_layer[layer].get('canonical_realized', 0)} | "
                f"{by_layer[layer].get('validated', 0)} | "
                f"{by_layer[layer].get('open', 0)} |"
            )
        open_items = [item for item in obligations if item.get("status") == "open"]
        if open_items:
            lines.extend(["", "Open obligations:", ""])
            for item in open_items:
                lines.append(
                    f"- `{item['obligation_id']}` "
                    f"(`{item.get('layer', 'unknown')}`): {item['statement']}"
                )

    lines.extend([
        "",
        "## Interpretation boundary",
        "",
        "This projection reports only the declared structural authority set above. `canonical_implementation` means repository authority for the declared object, not scientific endorsement. A module listed as runnable is not thereby verified; reference-realized obligations are independent correctness oracles rather than production completion; canonical realization is not empirical climate validation; and the absence of supporting evidence records keeps the corresponding scientific claim at its declared maturity. Likewise, an externally owned native capability is neither out of scope nor locally realized merely because it exists: Climate must bind and verify the integration boundary without shadowing the upstream implementation.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the generated projection")
    mode.add_argument("--check", action="store_true", help="fail if the checked-in projection does not match its declared inputs")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    rendered = render_status(ROOT)
    output = args.output

    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        print(f"wrote {output.relative_to(ROOT)}")
        return 0

    if not output.exists():
        print(f"generated structural projection missing: {output.relative_to(ROOT)}")
        return 1

    actual = output.read_text(encoding="utf-8")
    if actual != rendered:
        print(
            f"generated structural projection does not match declared authority inputs: "
            f"{output.relative_to(ROOT)}; run "
            "`python architecture/render_status.py --write`"
        )
        diff = difflib.unified_diff(
            actual.splitlines(),
            rendered.splitlines(),
            fromfile=str(output.relative_to(ROOT)),
            tofile="rendered structural projection",
            lineterm="",
        )
        for line in diff:
            print(line)
        return 1
    print(
        "generated structural projection matches declared authority inputs: "
        f"{output.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
