#!/usr/bin/env python3
"""Climate-statistics preservation across fixed two-layer EBM representations.

The stochastic physical trajectory is generated by the separately registered
internal-variability reference.  This module applies only fixture-declared
linear observation maps and their fixed Moore-Penrose pseudoinverses; it fits no
decoder and no stochastic model.

Statistics are kept distinct: mean-state error, zero-lag covariance error,
one-step lag-covariance error, and reservoir-specific variance error are
reported separately.  No aggregate representation score is produced.
"""
from __future__ import annotations

import argparse
import importlib.metadata
import json
import math
from pathlib import Path
import sys
from typing import Any, Mapping

ROOT = Path(__file__).resolve().parents[1]
if __package__ in {None, ""}:
    sys.path.insert(0, str(ROOT))

import numpy as np

from reference.two_layer_energy_balance import load_fixture as load_ebm_fixture
from reference.two_layer_stochastic_variability import (
    DEFAULT_STOCHASTIC_FIXTURE,
    generate_stochastic_trajectory,
    load_stochastic_fixture,
)


DEFAULT_EBM_FIXTURE = (
    ROOT / "fixtures" / "physics" / "two-layer-ebm-geoffroy-mean-v1.json"
)

REPRESENTATION_IDS = (
    "temperature_state",
    "surface_temperature_scalar",
    "redundant_surface_pair",
)


def _observation_matrix(spec: Mapping[str, Any]) -> np.ndarray:
    matrix = np.asarray(spec.get("observation_matrix"), dtype=float)
    if (
        matrix.ndim != 2
        or matrix.shape[1] != 2
        or matrix.shape[0] < 1
        or not np.isfinite(matrix).all()
        or not np.any(matrix)
    ):
        raise ValueError("representation observation_matrix must be finite shape-(m,2)")
    return matrix


def _statistics(states: np.ndarray, lag_steps: int) -> dict[str, np.ndarray]:
    values = np.asarray(states, dtype=float)
    if (
        values.ndim != 2
        or values.shape[1] != 2
        or values.shape[0] <= lag_steps
        or not np.isfinite(values).all()
    ):
        raise ValueError("statistics require a finite shape-(n,2) state trajectory")
    mean = np.mean(values, axis=0)
    centered = values - mean
    covariance = centered.T @ centered / values.shape[0]
    lag_covariance = (
        centered[:-lag_steps].T @ centered[lag_steps:]
        / (values.shape[0] - lag_steps)
    )
    return {
        "mean": mean,
        "covariance": covariance,
        "lag_covariance": lag_covariance,
    }


def _relative_matrix_error(observed: np.ndarray, reference: np.ndarray) -> float:
    left = np.asarray(observed, dtype=float)
    right = np.asarray(reference, dtype=float)
    if left.shape != right.shape or not np.isfinite(left).all() or not np.isfinite(right).all():
        raise ValueError("matrix-error inputs must be finite and shape matched")
    denominator = max(float(np.linalg.norm(right)), np.finfo(float).tiny)
    return float(np.linalg.norm(left - right) / denominator)


def _relative_scalar_error(observed: float, reference: float) -> float:
    left = float(observed)
    right = float(reference)
    if not math.isfinite(left) or not math.isfinite(right) or right <= 0.0:
        raise ValueError("variance comparison requires finite values and positive reference")
    return abs(left - right) / right


def analyze_stochastic_representation_statistics(
    ebm_fixture: dict[str, Any],
    stochastic_fixture: dict[str, Any],
) -> dict[str, Any]:
    specs = stochastic_fixture.get("representations")
    if not isinstance(specs, list):
        raise ValueError("stochastic fixture requires representation specifications")
    ids = [item.get("representation_id") for item in specs]
    if ids != list(REPRESENTATION_IDS):
        raise ValueError(
            "stochastic statistics v1 representation identities changed "
            "without a fixture version"
        )
    rcond = float(stochastic_fixture["pseudoinverse_rcond"])
    if not math.isfinite(rcond) or rcond <= 0.0:
        raise ValueError("pseudoinverse_rcond must be finite and positive")
    lag_steps = int(stochastic_fixture["lag_steps"])

    generated = generate_stochastic_trajectory(ebm_fixture, stochastic_fixture)
    states = np.asarray(generated["states_k"], dtype=float)
    reference = _statistics(states, lag_steps)
    reference_covariance = reference["covariance"]
    reference_lag = reference["lag_covariance"]
    surface_variance = float(reference_covariance[0, 0])
    deep_variance = float(reference_covariance[1, 1])
    if surface_variance <= 0.0 or deep_variance <= 0.0:
        raise RuntimeError("stochastic reference trajectory must excite both reservoirs")

    result: dict[str, Any] = {
        "fixture_id": stochastic_fixture["fixture_id"],
        "ebm_fixture_id": ebm_fixture["fixture_id"],
        "trajectory_digest": generated["trajectory_digest"],
        "lag_steps": lag_steps,
        "reference_statistics": {
            "mean_state_k": reference["mean"].tolist(),
            "state_covariance_k2": reference_covariance.tolist(),
            "lag_covariance_k2": reference_lag.tolist(),
            "surface_variance_k2": surface_variance,
            "deep_variance_k2": deep_variance,
        },
        "physical_budget": {
            "max_abs_total_budget_residual_w_m2": float(
                np.max(np.abs(generated["budget_residual_w_m2"]))
            ),
            "max_abs_direct_internal_storage_w_m2": float(
                np.max(np.abs(generated["direct_internal_storage_w_m2"]))
            ),
        },
        "representations": {},
        "implementation_versions": {
            "numpy": importlib.metadata.version("numpy"),
            "scipy": importlib.metadata.version("scipy"),
        },
    }

    for spec in specs:
        representation_id = spec["representation_id"]
        matrix = _observation_matrix(spec)
        observations = states @ matrix.T
        decoder = np.linalg.pinv(matrix, rcond=rcond)
        decoded = observations @ decoder.T
        decoded_statistics = _statistics(decoded, lag_steps)
        decoded_covariance = decoded_statistics["covariance"]
        decoded_lag = decoded_statistics["lag_covariance"]

        result["representations"][representation_id] = {
            "observation_dimension": int(matrix.shape[0]),
            "structural_observation_rank": int(np.linalg.matrix_rank(matrix)),
            "mean_state_l2_error_k": float(
                np.linalg.norm(decoded_statistics["mean"] - reference["mean"])
            ),
            "state_covariance_relative_frobenius_error": _relative_matrix_error(
                decoded_covariance, reference_covariance
            ),
            "lag_covariance_relative_frobenius_error": _relative_matrix_error(
                decoded_lag, reference_lag
            ),
            "surface_variance_relative_error": _relative_scalar_error(
                float(decoded_covariance[0, 0]), surface_variance
            ),
            "deep_variance_relative_error": _relative_scalar_error(
                float(decoded_covariance[1, 1]), deep_variance
            ),
        }

    full = result["representations"]["temperature_state"]
    surface = result["representations"]["surface_temperature_scalar"]
    redundant = result["representations"]["redundant_surface_pair"]
    result["full_state_covariance_error"] = float(
        full["state_covariance_relative_frobenius_error"]
    )
    result["full_state_lag_covariance_error"] = float(
        full["lag_covariance_relative_frobenius_error"]
    )
    result["redundant_vs_surface_covariance_error_delta"] = float(
        redundant["state_covariance_relative_frobenius_error"]
        - surface["state_covariance_relative_frobenius_error"]
    )
    result["redundant_vs_surface_lag_covariance_error_delta"] = float(
        redundant["lag_covariance_relative_frobenius_error"]
        - surface["lag_covariance_relative_frobenius_error"]
    )
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ebm-fixture", type=Path, default=DEFAULT_EBM_FIXTURE)
    parser.add_argument(
        "--stochastic-fixture",
        type=Path,
        default=DEFAULT_STOCHASTIC_FIXTURE,
    )
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    result = analyze_stochastic_representation_statistics(
        load_ebm_fixture(args.ebm_fixture),
        load_stochastic_fixture(args.stochastic_fixture),
    )
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True, allow_nan=False))
    else:
        for name, diagnostics in result["representations"].items():
            print(
                f"{name}: covariance="
                f"{diagnostics['state_covariance_relative_frobenius_error']:.6e} "
                "lag="
                f"{diagnostics['lag_covariance_relative_frobenius_error']:.6e}"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
